# Generated by Django 5.0.4 on 2024-04-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='barrio',
        ),
        migrations.AddField(
            model_name='venta',
            name='barrio',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
